# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: filestream
  id: php-filestream-id
  enabled: true
  paths:
    - /var/log/php-fpm/*.log
  fields_under_root: true
  fields:
    data_stream.dataset: php-fpm
    data_stream.namespace: default
    data_stream.type: vector-logs

- type: filestream
  id: mysql-filestream-id
  enabled: true
  paths:
    - /var/log/mariadb/*.log
  fields_under_root: true
  fields:
    data_stream.dataset: mysql
    data_stream.namespace: default
    data_stream.type: vector-logs

- type: filestream
  id: nginx-access-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields_under_root: true
  fields:
    data_stream.dataset: nginx-access
    data_stream.namespace: default
    data_stream.type: vector-logs

- type: filestream
  id: nginx-error-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields_under_root: true
  fields:
    data_stream.dataset: nginx-error
    data_stream.namespace: default
    data_stream.type: vector-logs

setup.ilm.enabled: false
setup.template.enabled: false

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

# ------------------------------ Vector Output -------------------------------
output.logstash:
  hosts: ["192.168.98.11:5045"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
