# ============================== Filebeat inputs ===============================

filebeat.inputs:
- type: filestream
  id: php-filestream-id
  enabled: true
  paths:
    - /var/log/php-fpm/*.log
  fields:
    type: logs
    service: php-fpm
    level: general

- type: filestream
  id: mysql-filestream-id
  enabled: true
  paths:
    - /var/log/mariadb/*.log
  fields:
    type: logs
    service: mysql
    level: general

- type: filestream
  id: nginx-access-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/access.log
  fields:
    type: logs
    service: nginx
    level: access

- type: filestream
  id: nginx-error-filestream-id
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields:
    type: logs
    service: nginx
    level: error

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["192.168.94.20:5044"]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
